global using Hoarding_managment.Models;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Hoarding_managment.Interface;
global using Hoarding_managment.Mapper;
global using Hoarding_managment.Data;
global using Hoarding_managment.Repository;
global using HoardingManagement.Interface;
global using Newtonsoft.Json;
global using OfficeOpenXml;
using System.Security.Cryptography;
using System.Text;